### ISSUE TITLE
needs code

### ISSUE THREAD

**Issue by DethRaid** [Strum355/vscode-mc-shader#1]
There's no code in this repo right now. Please add some

**Comment by Strum355** [comment]
This repo is following a new trend, similar to serverless. I'm adopting a code-less architecture :) it provides significant performance boosts compared to previous architectures.   
If this is not to your liking, please fork this repo and build upon it :) /s

**Comment by Strum355** [comment]
I gave in and added code :( unfortunately there were issues with the code-less architecture and we discovered that it was lacking some features that we cant live without
